###
GET http://localhost:5000/communities/latest?page=1
###
GET http://localhost:5000/communities/latest?page=2&lastId=608615a8b4cbbf0015ee3e90
###
GET http://localhost:5000/communities/find?cmd=id&value=60857bbede68e10ce73b6c13 

###
PATCH http://localhost:5000/communities/60857bbede68e10ce73b6c13/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1N2U1ODI2NmRjNDQ5YjIyMzk3YSIsImlhdCI6MTYxOTcxMTA0MSwiZXhwIjoxNjE5NzEyODQxfQ.g0Hrf3Vufc_zUgqUibIYn03t7qj2Yn9GuhQmrTXpNV4

###
PATCH http://localhost:5000/communities/60857bbede68e10ce73b6c13/join/606957e58266dc449b22397a?approve=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1ODA0ODI2NmRjNDQ5YjIyMzk3YiIsImlhdCI6MTYxOTcwOTc3MiwiZXhwIjoxNjE5NzExNTcyfQ.Gat8aopvrX2TVt7Y-ISoIS5jNWepbSXJ1plgFlCAfng
