###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email":"testuser2@gmail.com",
  "password":"123123123"
}
###
POST http://localhost:5000/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1ODA0ODI2NmRjNDQ5YjIyMzk3YiIsImlhdCI6MTYyMDE0MTY1MCwiZXhwIjoxNjIwMTQxNzEwfQ.MBA9z5iblVBuxOZvFh3WW_Ff8LMdr43k208slzYnLgw
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjAxNDE2NTAsImV4cCI6MTY1MTY5OTI1MH0.Wo1txxTB7UM3As7GEGmDE_Ms01yWIvMkznSaDkIJQ0M"
}

###
GET http://localhost:5000/communities/latest?page=1
###
GET http://localhost:5000/communities/latest?page=2&lastId=608615a8b4cbbf0015ee3e90
###
GET http://localhost:5000/communities/find?cmd=id&value=60857bbede68e10ce73b6c13 

###
PATCH http://localhost:5000/communities/60857bbede68e10ce73b6c13/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1N2U1ODI2NmRjNDQ5YjIyMzk3YSIsImlhdCI6MTYxOTcxMTA0MSwiZXhwIjoxNjE5NzEyODQxfQ.g0Hrf3Vufc_zUgqUibIYn03t7qj2Yn9GuhQmrTXpNV4

###
PATCH http://localhost:5000/communities/60857bbede68e10ce73b6c13/join/606957e58266dc449b22397a?approve=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1ODA0ODI2NmRjNDQ5YjIyMzk3YiIsImlhdCI6MTYxOTcwOTc3MiwiZXhwIjoxNjE5NzExNTcyfQ.Gat8aopvrX2TVt7Y-ISoIS5jNWepbSXJ1plgFlCAfng

###
POST http://localhost:5000/communities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1ODA0ODI2NmRjNDQ5YjIyMzk3YiIsImlhdCI6MTYyMDE5NTY1OSwiZXhwIjoxNjIwMTk2NTU5fQ.YOeWJOQHxn4lv-f5_EOc08JwMqU-5YI8hPjav-bplRs
Content-Type: multipart/form-data

{
  
}
###
POST http://localhost:5000/comments/post/609ce0c9f980832641f722f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1ODA0ODI2NmRjNDQ5YjIyMzk3YiIsImlhdCI6MTYyMTA3ODk1NCwiZXhwIjoxNjIxMDc5ODU0fQ.1WEmS1_VjQSUo8J-IpUgC4Q4bqZx_XIr0da-A4HV8fo
Content-Type: application/json

{
  "text":"New comment!"
}

###
POST http://localhost:5000/comments/609ce0c9f980832641f722f6/reply
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1ODA0ODI2NmRjNDQ5YjIyMzk3YiIsImlhdCI6MTYyMTQ3NzQ1NSwiZXhwIjoxNjIxNDc4MzU1fQ.Q_qSZ1aSMOu9q1WudoQIbY4NX5QbZQknfYpOf9woAi8
Content-Type: application/json

{
  "text":"New comment!"
}

###
PATCH  http://localhost:5000/user/follow/606957e58266dc449b22397a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjk1ODA0ODI2NmRjNDQ5YjIyMzk3YiIsImlhdCI6MTYyMTY4NDAxNSwiZXhwIjoxNjIxNjg0OTE1fQ.ix4N2zAKBls5STvfH6H3GUyvNb_hOGw4V8gR6zKIhWI